version: '3'

services:
    node-api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ecommerce-api
        restart: unless-stopped
        env_file: .env
        ports:
            - "3000:3000"
        networks:
            - app-network
        depends_on: 
            - mongodb

    mongodb:
        image: mongo:4.1.8-xenial
        container_name: ecommerce-db
        ports: 
            - "27017:27017"
        restart: unless-stopped
        env_file: .env
        volumes:
            - dbdata:/data/db
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
    
volumes:
    dbdata:
        driver: local